protocol = "kd-scientific-legato100"
doc = ""
traits = ["is-discrete", "has-position", "uses-uart", "uses-serial", "is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-kd-scientific"
bugtracker = "https://github.com/yaq-project/yaqd-kd-scientific/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-kd-scientific"
conda-forge = "https://anaconda.org/conda-forge/yaqd-kd-scientific"


[config]

[config.identifiers]
default = {"run" = 1, "stop" = 0}

[config.baud_rate]
default = 115200

[state]

[messages]

